name: Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main

            - name: 'Login to GitHub Container Registry'
              uses: docker/login-action@v1
              with:
                  registry: registry.cn-hangzhou.aliyuncs.com
                  username: ${{ secrets.ALIYUN_USERNAME }}
                  password: ${{ secrets.ALIYUN_PASSWORD }}

            - name: 'Build & Push'
              run: |
                  docker build . --tag registry.cn-hangzhou.aliyuncs.com/design-build/frontend:latest
                  docker push registry.cn-hangzhou.aliyuncs.com/design-build/frontend:latest
